### ISSUE TITLE
Allow GM sneakily editing health

### ISSUE THREAD

**Issue by eunomicZenith** [1000nettles/combat-numbers#10]
As a GM, I have a little secret: if an enemy turns out to be too frail, I can sneakily heal them to make the battle not be overly short, and, viceversa, if the battle's dragging on, I can sneakily decrease their health to get it over with faster.

I love this module, it's perfect for my campaign (set inside a virtual reality game with a pixel art aesthetic, essentially), but it'd prevent me from doing anything covertly like that. I'd want a way for the GM to edit health without the players seeing the numbers pop up.

**Comment by 1000nettles** [comment]
This is a really good idea, hadn't even thought of that. I'm not a good UX designer... Any ideas on functionality to let a GM turn it off for an HP modification? Potentially you could temporarily turn off the module from the module settings briefly, but that feels a bit laborious.

Your game also sounds awesome btw.

**Comment by gatesvp** [comment]
I think the rational way to do this is to have an on/off switch for the animation somewhere on the main screen. Like you can always turn off the module and then back on again, but that's not very smooth. So something on the main canvas would be better.

**Comment by eunomicZenith** [comment]
A switch to very quickly turn the module off, edit the health, then back on, sounds like a simple and convenient way to do it.

**Comment by 1000nettles** [comment]
Does adding another button in the toolbar make sense? Seems a little extreme, but I can't really see another place on the main canvas where we'd put it...

![Screen Shot 2020-11-15 at 10 08 49 PM](https://user-images.githubusercontent.com/425298/99218457-6009e580-278f-11eb-8f69-3f15a5b5284b.png)

**Comment by eunomicZenith** [comment]
It is a little extreme, but works fine as far as I'm concerned. It's not like my side bar is cluttered or anything.

**Comment by 1000nettles** [comment]
It'd maybe fit nice under the "Magic Wand" from the [FXMaster](https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster) module... I wonder if U-Man would be open to me adding another icon in the sub menu. 🤔 I can ask in Discord soon.

**Comment by 1000nettles** [comment]
After asking around in Discord, Calego suggested that we could potentially take an approach similar to [Enhanced Movement](https://foundryvtt.com/packages/EnhancedMovement/), which adds additional button(s) to the Token flyout menu.

Potentially we could add our own button here, or alternatively just the ability to toggle Combat Numbers on / off per token in the token configuration dialog. Thoughts?

<img width="477" alt="Screen Shot 2020-11-16 at 12 29 06 PM" src="https://user-images.githubusercontent.com/425298/99304956-f679ed80-2807-11eb-9433-b2b7c7fbd4e9.png">
<img width="505" alt="Screen Shot 2020-11-16 at 12 29 40 PM" src="https://user-images.githubusercontent.com/425298/99304946-f2e66680-2807-11eb-9416-454787a4e169.png">

**Comment by eunomicZenith** [comment]
I think having a button in the token flyout would be a little more intrusive than having it in the sidebar, and far more intrusive than having it under FX's wand. Having a button that enables/disables it for a specific token seems too cumbersome.

**Comment by 1000nettles** [comment]
Yup okay, fair enough. I'm envisioning some more canvas-level settings for Combat Numbers in the future. Let's just add it as another toolbar button itself.

**Comment by 1000nettles** [comment]
This has now been addressed in ff628263b0dfd10b46ff123ceb0e5f448e2d014d. We have added a new toolbar icon denoted by `#`, where you can turn Combat Numbers visibility on / off temporarily. Players, too, will not be able to see the numbers on their screens.

Added for the upcoming `v0.2.0` release coming very shortly... Stay tuned.

![Screen Shot 2020-11-20 at 3 30 42 PM](https://user-images.githubusercontent.com/425298/99859605-5bee1700-2b45-11eb-8756-c54600fb9cf9.png)

**Comment by 1000nettles** [comment]
This is now in v0.2.0 which has been released to the public: https://foundryvtt.com/packages/combat-numbers/
