### ISSUE TITLE
GM QoL

### ISSUE THREAD

**Issue by atleticano-snp** [1000nettles/combat-numbers#15]
Hey, your module is great! Enjoying it.

I can point here some suggestions, if possible to implement:

Some times as GM I want to hide the amount of dmg/healing from players, but let them know that something occured. In these cases, when HP is modified, instead showing the amount, it is possible to show a pre-built phrase, like: "Healead" (when HP up) // "Hit" (When HP fall) to hostile tokens?
-> This hide the amount of HP change, preventing players to fast discover NPC resistances - immunities.

Additionaly, some phrase when target is select but an attack misses to show: "Misses" or something.

Nice work bro!

**Comment by 1000nettles** [comment]
Hey! Thanks for the kind words.

I actually hadn't even considered resistances and immunities, that's a super good point. Do you envision this as a complete scene level change for all tokens (thus using a button in the controls toolbar), or on an individual token / actor themselves?

Misses might be tough because currently the listening happens right on the actor's health change itself. Any vision on a specific workflow on how "misses" could appear?

**Comment by atleticano-snp** [comment]
Unfortunately I don't know anything about JavaScript or any other language to help you, Sorry.
Maybe can post some random tips, but you probably already had them in mind:
* If HP increases then shows: 'Healed' instead the value.

* Perhaps the attack card can be used when there is a target "check Attack roll vs AC" (for DnD as example). 
If Attack roll <AC == "misses", 
if Attack roll> = AC == "hit" (if you want to hide from players); 
if d20 = 1 "badly misses" ## it may require adjusting the first one to exclude d20 = 1.

However different systems may require some attention.

Sorry, can't help you too much.

Anyway, its a great module, the last game was pretty funny the numbers poping out.

**Comment by 1000nettles** [comment]
Thanks for the great ideas here! I've created a new issue which provides more implementation details here: #19 

I also love the idea for a "Missed" text appearing, but currently the way checking and applying damage works it's a bit out of reach. Will revisit that later.

**Comment by 1000nettles** [comment]
"Masking" is now available in the latest release, v0.3.0.
