### ISSUE TITLE
Make the Tool group optional

### ISSUE THREAD

**Issue by apoapostolov** [1000nettles/combat-numbers#16]
For DM with a lot of tools from mods, please make the tool group optional (excuse the PF2 skin) via settings.

![image](https://user-images.githubusercontent.com/4083812/100016018-79d7a800-2de1-11eb-8141-5d66320028d7.png)

**Comment by 1000nettles** [comment]
Yup, considered this but was wondering if anyone would complain haha. This is low hanging fruit so I'll prioritize.

**Comment by 1000nettles** [comment]
This has been added in 8c07ccfa312698abd0b3916c7a2f9ae0f35b0590 and will be included in the next release. Stay tuned!

**Comment by 1000nettles** [comment]
Now in the latest release, v0.3.0.
