### ISSUE TITLE
Broke for PF2e in latest version (on Foundry 0.7.5 and PF2e 1.10.16.2317)

### ISSUE THREAD

**Issue by jacobjorvang** [1000nettles/combat-numbers#17]
Tried with and without sign, and tried changing the object path. Numbers just no longer show up.

**Comment by 1000nettles** [comment]
Sorry about that! I can take a look tonight.

Just checking, are you sure you didn't toggle the visibility in the Combat Numbers toolbar? (The # button and then the eye with a slash through it?)

**Comment by jacobjorvang** [comment]
I can't find that setting. Where is the toolbar?

**Comment by 1000nettles** [comment]
It's the vertical list of tools on the left-side of the canvas, to manipulate actors, put down templates, add tiles, etc.

**Comment by jacobjorvang** [comment]
Oh.. I don't have that. Maybe because I'm on 0.7.5 is the only thing I can think of

<img width="695" alt="Screenshot 2020-11-25 at 18 16 11" src="https://user-images.githubusercontent.com/5146879/100261031-7875bf00-2f4a-11eb-85eb-4fd1f1247c0a.png">

**Comment by 1000nettles** [comment]
Oh weird! That may be. I'll take a peek tonight and get back to you. Thanks for flagging the specific versions.

**Comment by 1000nettles** [comment]
If you're open to it, do you see anything fixed if you disable all other modules?

**Comment by jacobjorvang** [comment]
No. Tried 5e too.

**Comment by 1000nettles** [comment]
I have fixed this in the latest release - v0.2.1. Updating the module in FoundryVTT should address your concerns. Thanks.

**Comment by jacobjorvang** [comment]
Thank you, works beautifully now!
Just FYI, there is some kind of interaction with the Token Drag Visibility mod when toggling the CN visibility button:

Uncaught TypeError: Cannot read property 'length' of undefined
    at checkDragBegin (tokendragvisibility.js:38)

But everything looks to be working, so it's probably nothing.

https://foundryvtt.com/packages/token-drag-visibility/

**Comment by 1000nettles** [comment]
Odd! I'm going to chalk it up to a Token Drag Visibility module issue as that it hasn't been updated for a long time and is supporting v0.6.2 max.

Thanks for reporting back that it's working now.
