### ISSUE TITLE
When setting a condition on an actor: "TypeError: Cannot read property 'getIsVisible' of undefined"

### ISSUE THREAD

**Issue by jacobjorvang** [1000nettles/combat-numbers#18]
<img width="521" alt="Screenshot 2020-11-27 at 00 07 44" src="https://user-images.githubusercontent.com/5146879/100396238-b6570e00-3044-11eb-8dbc-3aa2c06a5740.png">

**Comment by jacobjorvang** [comment]
Foundry 0.7.5 and PF2e 1.10.16.2317. Test world. Only mod enabled.

**Comment by 1000nettles** [comment]
Thanks for this - I assume this is why the other issue exists too. Got busy with fulltime job last night but should have time tonight to take a peek.

**Comment by jacobjorvang** [comment]
Could very well be and I just didn't notice it before.

**Comment by 1000nettles** [comment]
I have fixed this in the latest release - v0.2.1. Updating the module in FoundryVTT should address your concerns. Thanks.
