### ISSUE TITLE
Create "masking" option allowing a user to mask HP modifications

### ISSUE THREAD

**Issue by 1000nettles** [1000nettles/combat-numbers#19]
As brought up in issue #15 - it would be beneficial for a user to allow masking their HP modifications but still let other users know that a change occurred. This is useful for things like, masking resistances or vulnerabilities.

Let's implement this as text like, "Hit" and "Healed". It would be great if a user could adjust this in their own settings.

**Comment by apoapostolov** [comment]
Also we need an API method to skip the Combat Number in Macros.

For example the code below is my "give the creature one more turn" macro,w which is now exposed to players:

for ( let token of canvas.tokens.controlled ) {
  let HP = token.actor.data.data.attributes.hp.value;
  let Max_HP = token.actor.data.data.attributes.hp.max;
  token.actor.update({
    "data.attributes.hp.value": HP + 5,
    "data.attributes.hp.max" : Max_HP + 5
  });
};

**Comment by 1000nettles** [comment]
This has now been resolved with 83b2174841b2d520b81879aa475113e1fde711ab and will be available in the next release.
