### ISSUE TITLE
Make the location of the HP values into a module setting to support other systems

### ISSUE THREAD

**Issue by xdy** [1000nettles/combat-numbers#2]
I.e. the values used on line 19-20 in actorCalculator.js
```
    const origHp = _.get(origEntity, 'data.data.attributes.hp.value', null);
    const newHp = _.get(changedEntity, 'data.attributes.hp.value', null);
```
For instance, in the system I'm working on (Twodsix), the closest equivalent would be 'data.data.hits'

If this was possible systems could include code to set that module setting if the module is loaded, and/or individual users could just set it themselves to suit whatever system they are using.

**Comment by 1000nettles** [comment]
This is a brilliant idea @xdy thanks for sharing. I'm thinking this is the best approach instead of strictly hardcoding the HP value locations within the module itself per system.

I may develop this so the module is "smart" and can locate the HP value locations automatically dependant on system, but as you mentioned, give other systems the ability to set this themselves. And additionally, allow an admin to set this.

**Comment by Vass1979** [comment]
Yes please! This x 1000!!!

**Comment by gatesvp** [comment]
> If this was possible systems could include code to set that module setting if the module is loaded, and/or individual users could just set it themselves to suit whatever system they are using

This is the first thing I thought of when trying to port this to a homebrew system, it really seems like the whole thing is predicated on a single value, so you might as well make that value a module setting.

And honestly, if it ships with D&D and PF2E by default, that's fine. You can also include the required string in the text for the module description.

**Comment by 1000nettles** [comment]
Yup definitely, this is next up in development sometime this coming week. Part of getting to PF2E was to get my ducks in a row so that just replacing the necessary HP value string is doable. Stay tuned!

**Comment by 1000nettles** [comment]
I got a PR up for this issue that I'm going to review tomorrow with fresh eyes.

**Comment by 1000nettles** [comment]
This will be going out with this weekend's v0.2.0 release.

**Comment by 1000nettles** [comment]
This is now in v0.2.0 which has been released to the public: https://foundryvtt.com/packages/combat-numbers/
