### ISSUE TITLE
Add ability to set default masking state

### ISSUE THREAD

**Issue by TPNils** [1000nettles/combat-numbers#26]
When using "Mask Combat Number Display", it resets when I reload the page and shows the full numbers again.

**Comment by Silvestrae** [comment]
Hey Spy, as a temporary way to make the numbers always masked, open the combat-numbers.js file, do a search for the function getIsMask and replace 

```
getIsMask() {
    return this.isMask;
  }
```
with 
```
getIsMask() {
    return true;
  }
```
Do note that you cannot toggle the numbers back on doing it this way. It will always be masked!

**Comment by 1000nettles** [comment]
A default mask state can now be set with the "Mask Default State" setting in module settings. Cheers.
