### ISSUE TITLE
Suggestion: Allow custom fonts specifications in the Settings

### ISSUE THREAD

**Issue by megahead11** [1000nettles/combat-numbers#30]
Hi! Love this module so far, it's been really good for adding feedback in combat for my players, so I definitely appreciate you adding this!

I would just like to suggest that it would be nice to allow GMs to define the font, colors, and sizing in an interface using the Module Settings. I have a couple of custom fonts loaded into my server for a few CSS things, so I think it'd be nice to be able to use those without having to manually edit the js file each time the mod's updated. This would really make the module shine for me! 
Thanks!

**Comment by 1000nettles** [comment]
Hey! Thanks for the kind words. This is up next in feature development. Good to know you're loading custom fonts, I'll make sure to add a way to specify a fontname in a textbox too.

Also, dynamic sizing based on gridsize will be up next too.

**Comment by 1000nettles** [comment]
Good news - this was just added in the latest version (v1.0.0). Go check it out!
