### ISSUE TITLE
Feature Request: Display time delay

### ISSUE THREAD

**Issue by MrManlyMan** [1000nettles/combat-numbers#39]
Hey, great module. It would be awesome though if you could add an option to delay the display of the combat numbers. The reason is combat animations. I personally use animations for flavor and it would be awesome if I could delay the damage numbers so that they pop up in sync with the animation hitting the enemy and not before the animation goes through.

**Comment by 1000nettles** [comment]
Good idea, this is now available in the latest version, v1.1.0.
