### ISSUE TITLE
Please add "pf2e" to module.json as it has been tested and works

### ISSUE THREAD

**Issue by jacobjorvang** [1000nettles/combat-numbers#4]
Except that on the very first time applying damage to a token after placing it, there is no pop-up, but I don't know if this is only on pf2e. Even if it is, the module still works aside from this.

**Comment by 1000nettles** [comment]
Hey there! I am able to re-create exactly what you mentioned. As this looks like low-hanging fruit, I'll try to get PF2E added soon. :)

**Comment by 1000nettles** [comment]
This has now been addressed in the latest release, v0.1.4. I also managed to fix the bug where a new token placed on the scene wouldn't have the combat numbers displayed on the first HP change.

Enjoy!
