### ISSUE TITLE
Feature Request: Variable timing

### ISSUE THREAD

**Issue by Astudeba** [1000nettles/combat-numbers#40]
I love this module, but my one request is the option to set a custom amount of time for the number to stay on screen.

**Comment by jbhaywood** [comment]
Came here to make the same request. I don't need the numbers to stay on screen as long as they do, especially since it seems like only two characters can have numbers showing on them at a time.

**Comment by 1000nettles** [comment]
Good idea, this is now available in the latest version, v1.1.0.
