### ISSUE TITLE
Only shows two combat numbers at a time

### ISSUE THREAD

**Issue by jbhaywood** [1000nettles/combat-numbers#41]
Maybe it's just something with my setup, but if for example, I select five characters and adjust the health on all at once, combat numbers only show up on two of them. And if I adjust the health on a character while two others already have numbers showing, no combat number will pop up on the one I'm changing.

**Comment by 1000nettles** [comment]
That's really weird! I just tried this on my local and I'm able to update 10 tokens at once, and they all show their respective Combat Numbers.

Note that if tokens are healed and already have full health, the Combat Numbers will not be displayed.

**Comment by jbhaywood** [comment]
I tried again and everything seems to be working correctly. Don't know what was going on before. I tried it on multiple tokens, both using damage and healing. But whatever. It's good now.
