### ISSUE TITLE
Broken in v9T2

### ISSUE THREAD

**Issue by apoapostolov** [1000nettles/combat-numbers#53]
Started testing all my modules in v9 Testing 2 release as I use over 180. I found that Combat Numbers is broken and disables the canvas (black canvas screen).  The related error is:

TypeError: Cannot read properties of undefined (reading 'combatNumbers')
[No packages detected]
    at Canvas._createGroups (foundry.js:19340)
    at Canvas.initialize (foundry.js:19266)
    at Game.initializeCanvas (foundry.js:5479)
    at async Game.setupGame (foundry.js:5353)
    at async Game._initializeGameView (foundry.js:6291)
    at async Game.initialize (foundry.js:5249)

**Comment by BlackMoons** [comment]
Can confirm error persists in V9 stable release. Also I think this module still does a much better job then the new status text and is still very much needed.

**Comment by 1000nettles** [comment]
Thanks for letting me know, and that it is still needed even in v9. I'll take a look soon and if not soon, right after the holidays.

**Comment by BlackMoons** [comment]
Thanks for writing it and considering updating it! This module does a much better job at combat numbers and lets you do way more configuration, with better animation/duration too. Core V9 combat numbers just scrolls up at a constant rate and goes really high and has 0 configuration options besides on/off (So at least we can turn it off so it won't interfere with this mod)

That said, the status effect text is kinda nifty. Maybe a future feature for combat numbers?

**Comment by 1000nettles** [comment]
Re: the status effect text, not a bad idea - I'm currently swamped with other projects right now though :( If someone made a PR I'd be happy to take a look at it.

Regardless, v9.x support added and released now!
