### ISSUE TITLE
Prevents canvas from rendering [v9] [DnD4e]

### ISSUE THREAD

**Issue by FoxLee** [1000nettles/combat-numbers#55]
I just found this module and I love it, but after moving from v8.9 to v9 it seems to have a huge problem in my game worlds. Since nobody else seems to have run into it, it might be to do with the game system I'm using (D&D4e). Activating this module causes an error that stops the canvas from rendering at all, leaving only a black canvas and unusable toolbar.

For clarity, although it's not a supported system, I had not seen any errors using Combat Numbers with 4e under Foundry v8.9.

Here's the error in a basic 4e environment, with just the system and its libwrapper dependency active:
![image](https://user-images.githubusercontent.com/10067730/147169006-ab41d513-6a35-410f-9fde-a952a7235e6c.png)

In case it helps, here's the error with libwrapper deactivated:
![image](https://user-images.githubusercontent.com/10067730/147168773-40527fb4-18c8-4e6b-b8ec-2a23bfd17db6.png)

**Comment by 1000nettles** [comment]
Hey there! Thanks for the report. I just released an update for this issue today, can you please confirm you are testing on the latest Combat Numbers version?

**Comment by FoxLee** [comment]
Hmm, I _thought_ I was since Foundry can't find a newer version when I try to update. But it also reports version 1.2.0, which looks old based on the version here. I'll try to force a manual update and see if that does the trick.

**Comment by FoxLee** [comment]
Yup, that took care of it >3>; Well, I learned not to trust the updater I guess <XD Sorry for wasting your time there!

**Comment by 1000nettles** [comment]
Ha all good!
