### ISSUE TITLE
stronger visual differentiation for healing vs. damage

### ISSUE THREAD

**Issue by troygoode** [1000nettles/combat-numbers#9]
Right now the white text vs. light-green text is hard to differentiate. Perhaps consider showing healing numbers prefixed with a plus sign? e.g. `+10`?

**Comment by 1000nettles** [comment]
Not a bad idea. This is a pretty straightforward setting to add (adding a `+` modifier).

In the future, users will be able to customize the healing vs. damage number colours as well.

**Comment by 1000nettles** [comment]
This has now been addressed in 3dd30f0bc69a2c116762902d4be0ff62c271c726. There will be an option to add `+` and `-` modifiers in front of the numbers, and the healing green has changed for visibility.

**Comment by 1000nettles** [comment]
This will be included in the upcoming `v0.2.0` release. Stay tuned...

**Comment by 1000nettles** [comment]
This is now in v0.2.0 which has been released to the public: https://foundryvtt.com/packages/combat-numbers/

**Comment by troygoode** [comment]
Installed it and it works great – thanks!
